In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[7305, 7115, 5121, 6580],
 [7305, 7115, 5121, 6795],
 [7305, 9515, 5121, 6038],
 [1186, 7554, 2507, 7669, 4250],
 [1186, 7554, 2507, 7669, 4898],
 [7376, 7305, 9496, 5121, 5454],
 [5648, 5795, 2225, 7669]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7305 7115 5121 6580]
 [   0    0    0    0 7305 7115 5121 6795]
 [   0    0    0    0 7305 9515 5121 6038]
 [   0    0    0 1186 7554 2507 7669 4250]
 [   0    0    0 1186 7554 2507 7669 4898]
 [   0    0    0 7376 7305 9496 5121 5454]
 [   0    0    0    0 5648 5795 2225 7669]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 193ms/step


array([[[-0.02179303, -0.02037107, -0.03858091, -0.01905073,
         -0.03786147,  0.00459494, -0.04331455,  0.04633496,
          0.00740306,  0.03500596],
        [-0.02179303, -0.02037107, -0.03858091, -0.01905073,
         -0.03786147,  0.00459494, -0.04331455,  0.04633496,
          0.00740306,  0.03500596],
        [-0.02179303, -0.02037107, -0.03858091, -0.01905073,
         -0.03786147,  0.00459494, -0.04331455,  0.04633496,
          0.00740306,  0.03500596],
        [-0.02179303, -0.02037107, -0.03858091, -0.01905073,
         -0.03786147,  0.00459494, -0.04331455,  0.04633496,
          0.00740306,  0.03500596],
        [ 0.04081178, -0.00887676,  0.04984633,  0.04569734,
         -0.03457688,  0.01058381,  0.01059241,  0.00552753,
         -0.01303587,  0.01840146],
        [ 0.0062459 ,  0.04830198, -0.03539271,  0.02376441,
          0.0116833 , -0.02161813,  0.049139  , -0.01127452,
          0.04914315,  0.04542035],
        [ 0.04783039,  0.03373334, -0.04656273,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7305, 7115, 5121, 6580])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 53ms/step


array([[-0.02179303, -0.02037107, -0.03858091, -0.01905073, -0.03786147,
         0.00459494, -0.04331455,  0.04633496,  0.00740306,  0.03500596],
       [-0.02179303, -0.02037107, -0.03858091, -0.01905073, -0.03786147,
         0.00459494, -0.04331455,  0.04633496,  0.00740306,  0.03500596],
       [-0.02179303, -0.02037107, -0.03858091, -0.01905073, -0.03786147,
         0.00459494, -0.04331455,  0.04633496,  0.00740306,  0.03500596],
       [-0.02179303, -0.02037107, -0.03858091, -0.01905073, -0.03786147,
         0.00459494, -0.04331455,  0.04633496,  0.00740306,  0.03500596],
       [ 0.04081178, -0.00887676,  0.04984633,  0.04569734, -0.03457688,
         0.01058381,  0.01059241,  0.00552753, -0.01303587,  0.01840146],
       [ 0.0062459 ,  0.04830198, -0.03539271,  0.02376441,  0.0116833 ,
        -0.02161813,  0.049139  , -0.01127452,  0.04914315,  0.04542035],
       [ 0.04783039,  0.03373334, -0.04656273,  0.00770495, -0.03432232,
         0.01816029,  0.04838702,  0.03097092